### ISSUE TITLE
Please cut another release

### ISSUE THREAD

**Issue by cacack** [adammck/terraform-inventory#146]
We'd like to pick up #139 and would rather not build ourself.

Thanks!

**Comment by kdouglas-modusbox** [comment]
+1 I've already built from source and confirmed the issue I was having is resolved, but would much rather consume a release than having to maintain my own build and/or binary separately

**Comment by sokoow** [comment]
I don't think it's solved just yet, I still get:

```
Error reading tfstate file: 0.12 format error: <nil>; pre-0.12 format error: <nil> (nil error means no content/modules found in the respective format)
```
when reading states from TF v0.12.24+

**Comment by sokoow** [comment]
and packet.net is broken too:

```
$ terraform version
Terraform v0.12.24
+ provider.null v2.1.2
+ provider.packet v3.0.0

Your version of Terraform is out of date! The latest version
is 0.13.0. You can update by downloading from https://www.terraform.io/downloads.html

$ terraform-inventory  --list
Error reading tfstate file: 0.12 format error: <nil>; pre-0.12 format error: <nil> (nil error means no content/modules found in the respective format)
```

**Comment by jpmat296** [comment]
> We'd like to pick up #139 and would rather not build ourself.

I have published a new "dev" release from my fork:
https://github.com/jpmat296/terraform-inventory/releases
